# Generated by Django 3.2 on 2021-07-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCycleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_date', models.DateTimeField()),
                ('cycle_average', models.IntegerField()),
                ('period_average', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('ovulation_date', models.DateTimeField()),
                ('fertility_window_start', models.DateTimeField()),
                ('fertility_window_end', models.DateTimeField()),
                ('pre_ovulation_window_start', models.DateTimeField()),
                ('pre_ovulation_window_end', models.DateTimeField()),
                ('post_ovulation_window_start', models.DateTimeField()),
                ('post_ovulation_window_end', models.DateTimeField()),
                ('no_longer_valid', models.BooleanField(default=False)),
                ('create_cycle_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='period_estimator.createcyclerequest')),
            ],
        ),
    ]
