# Generated by Django 3.2 on 2021-07-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('period_estimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodcycle',
            name='create_cycle_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_cycle_request', to='period_estimator.createcyclerequest'),
        ),
    ]
